services:
  # 1. Base de Datos MySQL
  mysql:
    image: mysql:8.0
    container_name: erp_general_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PodocureSeguro2026
      MYSQL_DATABASE: gestion_db
    ports:
      - "3309:3306" # Mapeado al 3309 para no chocar con otros proyectos
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. Backend (NodeJS + Express + Prisma)
  backend:
    build: ./backend
    container_name: erp_general_backend
    restart: always
    ports:
      - "9000:9000"
    
    environment:
      PORT: "9000"
      # Conexión a la base de datos (host = nombre del servicio 'mysql')
      DATABASE_URL: "mysql://root:PodocureSeguro2026@mysql:3306/gestion_db"
      JWT_SECRET: "2026Podocure56107"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  # 3. Frontend (React + Vite)
  frontend:
    build: ./frontend
    container_name: erp_general_frontend
    restart: always
    ports:
      - "5177:5173" # Mapeado al 5177 para no chocar con otros proyectos
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Necesario para hot-reload en Windows
    depends_on:
      - backend

volumes:
  mysql_data:
